export function personaCliUsage(invocationName: string): string {
  return [
    `Usage: ${invocationName} <command> [args...]`,
    "",
    "Commands:",
    "  init                         Install Persona Harness config and start the backend profile interview.",
    "  bootstrap backend            Fill missing backend profile/policy/plan workflow pieces.",
    "  intake                       Create a draft backend project profile for planning.",
    "  plan                         Create a blackbear architecture plan draft before implementation.",
    "  policy                       Create backend-only policy overlay files.",
    "  history                      Archive completed workflow artifacts into local history.",
    "  language                     Show supported user languages for intake and workflow prompts.",
    "  bearshell <command> [args...] Run a bounded command helper for repo inspection and smoke tests.",
    "  workflow check               Report plan/report/evidence workflow status.",
    "  workflow implement           Print the single AI-facing implementation rail.",
    "  workflow continue            Print the accepted-plan continuation prompt.",
    "  workflow roles               Write non-autonomous workflow role boundaries.",
    "  workflow draft --stdin       Draft requirements from a vague product idea and stop for review.",
    "  workflow approve requirements Mark drafted requirements accepted before ticket splitting.",
    "  workflow capture --stdin     Save prompt requirements as the latest workflow source.",
    "  workflow split [source.md]   Split requirement Step sections into workflow task cards.",
    "  workflow next                Print the next pending workflow ticket.",
    "  workflow archive <ticket>    Move a completed ticket from work to immutable history.",
    "  workflow start implement     Print the AI-facing implementation workflow rail.",
    "  workflow finish implement    Block final answer until implementation workflow evidence is complete.",
    "  workflow guard implement     Block implementation until plan workflow state is ready.",
    "  workflow guard final         Block final answer until report/evidence workflow state is ready.",
    "  doctor                       Diagnose local OpenCode and Persona Harness installation state.",
    "  evidence summary             Write .persona/evidence/summary.md from raw evidence files.",
    "  smoke                        Write .persona/workflow/smoke-report.md.",
    "  feedback                     Write .persona/workflow/feedback-report.md.",
    "  review backend-shape         Write report-only backend Clean Code shape observations.",
    "",
    "Examples:",
    `  ${invocationName} init`,
    `  ${invocationName} bootstrap backend`,
    `  ${invocationName} intake`,
    `  ${invocationName} plan`,
    `  ${invocationName} policy init`,
    `  ${invocationName} language`,
    `  ${invocationName} history --id run-001`,
    `  ${invocationName} bearshell npm test`,
    `  ${invocationName} workflow check`,
    `  ${invocationName} workflow implement`,
    `  ${invocationName} workflow continue`,
    `  ${invocationName} workflow roles`,
    `  ${invocationName} workflow draft --stdin`,
    `  ${invocationName} workflow approve requirements`,
    `  ${invocationName} workflow capture --stdin`,
    `  ${invocationName} workflow split`,
    `  ${invocationName} workflow split README.md`,
    `  ${invocationName} workflow next`,
    `  ${invocationName} workflow archive step-1`,
    `  ${invocationName} workflow start implement`,
    `  ${invocationName} workflow finish implement`,
    `  ${invocationName} workflow guard implement`,
    `  ${invocationName} workflow guard final`,
    `  ${invocationName} doctor`,
    `  ${invocationName} evidence summary`,
    `  ${invocationName} smoke`,
    `  ${invocationName} feedback`,
    `  ${invocationName} review backend-shape`,
    `  ${invocationName} bearshell --shell 'git status --short && npm test'`,
  ].join("\n")
}
