export function personaCliUsage(invocationName: string): string {
  return [
    `Usage: ${invocationName} <command> [args...]`,
    "",
    "Commands:",
    "  version                      Print the packaged Persona Harness version.",
    "  init                         Install Persona Harness config and OpenCode plugin config.",
    "  bootstrap backend            Fill backend AGENTS/profile/policy/plan workflow pieces.",
    "  intake                       Create a draft backend project profile for planning.",
    "  instructions infer backend   Infer backend instruction candidates with provenance.",
    "  instructions adopt           Copy inferred candidates into adopted policy for review.",
    "  instructions check           Check adopted instruction rules without blocking finish.",
    "  plan                         Create a blackbear architecture plan draft before implementation.",
    "  policy                       Create backend-only policy overlay files.",
    "  history                      Archive completed workflow artifacts into local history.",
    "  language                     Show supported user languages for intake and workflow prompts.",
    "  observe [--json] <path>      Run report-only Java observer checks on a file or directory.",
    "  bearshell <command> [args...] Run a bounded command helper for repo inspection and smoke tests.",
    "  workflow check               Report plan/report/evidence workflow status.",
    "  workflow implement           Print the single AI-facing implementation rail.",
    "  workflow test                Record opt-in TDD red evidence from PH-run Gradle/JUnit.",
    "  workflow tdd                 Print read-only TDD red→green status and next action.",
    "  workflow continue            Print the accepted-plan continuation prompt.",
    "  workflow roles               Write non-autonomous workflow role boundaries.",
    "  workflow draft --stdin       Draft requirements from a vague product idea and stop for review.",
    "  workflow approve requirements Mark drafted requirements accepted before ticket splitting.",
    "  workflow capture --stdin     Save prompt requirements as the latest workflow source.",
    "  workflow split [source.md]   Split requirement Step sections into workflow task cards.",
    "  workflow next                Print the next pending workflow ticket.",
    "  workflow archive <ticket>    Move a completed ticket from work to immutable history.",
    "  workflow start implement     Print the AI-facing implementation workflow rail.",
    "  workflow finish implement    Block final answer until implementation workflow evidence is complete.",
    "  workflow guard implement     Block implementation until plan workflow state is ready.",
    "  workflow guard final         Block final answer until report/evidence workflow state is ready.",
    "  doctor                       Diagnose local OpenCode and Persona Harness installation state.",
    "  evidence summary             Write .persona/evidence/summary.md from raw evidence files.",
    "  evidence metrics [--json]    Aggregate local token/tool/MCP/finish evidence when present.",
    "  evidence ab-report [--json]  Aggregate local structured A/B evidence without claims.",
    "  evidence pminus-report [--json] Read A/B evidence as keep/downgrade decision support.",
    "  smoke                        Write .persona/workflow/smoke-report.md.",
    "  feedback                     Write .persona/workflow/feedback-report.md.",
    "  review backend-shape         Write report-only backend Clean Code shape observations.",
    "",
    "Examples:",
    `  ${invocationName} version`,
    `  ${invocationName} --version`,
    `  ${invocationName} init`,
    `  ${invocationName} bootstrap backend`,
    `  ${invocationName} intake`,
    `  ${invocationName} instructions infer backend`,
    `  ${invocationName} instructions adopt --min-confidence high`,
    `  ${invocationName} instructions check --json`,
    `  ${invocationName} plan`,
    `  ${invocationName} policy init`,
    `  ${invocationName} language`,
    `  ${invocationName} observe --json example/`,
    `  ${invocationName} history --id run-001`,
    `  ${invocationName} bearshell npm test`,
    `  ${invocationName} workflow check`,
    `  ${invocationName} workflow implement`,
    `  ${invocationName} workflow test`,
    `  ${invocationName} workflow tdd`,
    `  ${invocationName} workflow continue`,
    `  ${invocationName} workflow roles`,
    `  ${invocationName} workflow draft --stdin`,
    `  ${invocationName} workflow approve requirements`,
    `  ${invocationName} workflow capture --stdin`,
    `  ${invocationName} workflow split`,
    `  ${invocationName} workflow split README.md`,
    `  ${invocationName} workflow next`,
    `  ${invocationName} workflow archive step-1`,
    `  ${invocationName} workflow start implement`,
    `  ${invocationName} workflow finish implement`,
    `  ${invocationName} workflow guard implement`,
    `  ${invocationName} workflow guard final`,
    `  ${invocationName} doctor`,
    `  ${invocationName} evidence summary`,
    `  ${invocationName} evidence metrics --json`,
    `  ${invocationName} evidence ab-report --json`,
    `  ${invocationName} evidence pminus-report --json`,
    `  ${invocationName} smoke`,
    `  ${invocationName} feedback`,
    `  ${invocationName} review backend-shape`,
    `  ${invocationName} bearshell --shell 'git status --short && npm test'`,
  ].join("\n")
}
