import type { CliHelpLocale } from "./help-locale.js"

function englishUsage(invocationName: string): string {
  return [
    `Usage: ${invocationName} <command> [args...]`,
    "",
    "Product tracks:",
    "  Workflow Integrity                 Evidence and completion gates.",
    "  Context Personalization (Experimental)  Local, default-off Context guidance.",
    "",
    "Public commands:",
    "  version                      Print the packaged Persona Harness version.",
    "  init                         Install Persona Harness config and OpenCode plugin config.",
    "  attach [--yes]               Prepare an existing Java/Spring/Gradle project for the workflow.",
    "  go <goal> | --stdin           Host-neutral single entry from a concrete goal to the current ticket and implementation rail.",
    "  doctor                       Diagnose local OpenCode and Persona Harness installation state.",
    "  update                       Control opt-in project-local automatic Persona Harness updates.",
    "  plugin path <host>           Print a verified Antigravity, Codex, or Claude plugin path.",
    "  observe <path>               Report Java/Spring observer findings for a file or directory.",
    "  context                      Inspect the experimental default-off Context track.",
    "  authority                    Inspect or enroll bounded external consumer authority.",
    "  feedback                     Write a project feedback template or capture a bounded owner dogfood event.",
    "  philosophy                   Inspect and resolve the local personalization profile.",
    "",
    "Examples:",
    `  ${invocationName} version`,
    `  ${invocationName} --version`,
    `  ${invocationName} init`,
    `  ${invocationName} attach --yes`,
    `  ${invocationName} go "Add a task creation endpoint."`,
    `  printf "Add task creation." | ${invocationName} go --stdin`,
    `  ${invocationName} doctor`,
    `  ${invocationName} update enable --yes`,
    `  ${invocationName} update repair --yes`,
    `  ${invocationName} plugin path codex`,
    `  ${invocationName} observe src/main/java`,
    `  ${invocationName} context status`,
    `  ${invocationName} authority status`,
    `  ${invocationName} feedback dogfood source-read-runtime-unavailable`,
    `  ${invocationName} philosophy status`,
  ].join("\n")
}

function koreanUsage(invocationName: string): string {
  return [
    `사용법: ${invocationName} <명령> [인자...]`,
    "",
    "제품 트랙:",
    "  Workflow Integrity                 근거와 완료 게이트입니다.",
    "  Context Personalization (Experimental)  로컬 기본 비활성 Context 안내입니다.",
    "",
    "공개 명령:",
    "  version                      패키지된 Persona Harness 버전을 출력합니다.",
    "  init                         Persona Harness 설정과 OpenCode 플러그인 설정을 설치합니다.",
    "  attach [--yes]               기존 Java/Spring/Gradle 프로젝트를 workflow에 연결합니다.",
    "  go <goal> | --stdin           구체적인 목표를 현재 ticket과 구현 rail로 연결하는 단일 진입점입니다.",
    "  doctor                       로컬 OpenCode 및 Persona Harness 설치 상태를 진단합니다.",
    "  update                       프로젝트별 자동 Persona Harness 업데이트를 제어합니다.",
    "  plugin path <host>           검증된 Antigravity, Codex 또는 Claude 플러그인 경로를 출력합니다.",
    "  observe <path>               파일 또는 디렉터리의 Java/Spring observer 관측 결과를 보고합니다.",
    "  context                      실험적 기본 비활성 Context 트랙을 확인합니다.",
    "  authority                    제한된 외부 consumer authority 상태를 확인하거나 등록합니다.",
    "  feedback                     프로젝트 feedback 템플릿 또는 제한된 owner dogfood event를 기록합니다.",
    "  philosophy                   개인화 profile을 확인하고 결정을 append-only로 관리합니다.",
    "",
    "도움말 언어 선택: --lang en 또는 --lang ko",
    "",
    "예시:",
    `  ${invocationName} version`,
    `  ${invocationName} --version`,
    `  ${invocationName} init`,
    `  ${invocationName} attach --yes`,
    `  ${invocationName} go "작업 생성 endpoint를 추가해줘."`,
    `  printf "작업 생성 endpoint를 추가해줘." | ${invocationName} go --stdin`,
    `  ${invocationName} doctor`,
    `  ${invocationName} update enable --yes`,
    `  ${invocationName} update repair --yes`,
    `  ${invocationName} plugin path codex`,
    `  ${invocationName} observe src/main/java`,
    `  ${invocationName} context status`,
    `  ${invocationName} authority status`,
    `  ${invocationName} feedback dogfood source-read-runtime-unavailable`,
    `  ${invocationName} philosophy status`,
  ].join("\n")
}

export function personaCliUsage(invocationName: string, locale: CliHelpLocale = "en"): string {
  return locale === "ko" ? koreanUsage(invocationName) : englishUsage(invocationName)
}
