export function createImplementationReportTemplate(inputLines: readonly string[]): string {
  return [
    "# Implementer Implementation Report",
    "",
    "Role: `implementer`",
    "Status: template",
    "",
    "## Inputs",
    "",
    ...inputLines,
    "",
    "Plan source: `.persona/workflow/plan.md`",
    "",
    "## Read Coverage",
    "",
    "- README read method:",
    "- README ranges read:",
    "- Project profile read method:",
    "- Project profile ranges read:",
    "- Plan read method:",
    "- Plan ranges read:",
    "- Java role discovery method:",
    "- Java role files discovered:",
    "- Java role files read:",
    "- Unread ranges:",
    "- Read evidence notes:",
    "",
    "## Implemented Files",
    "",
    "- [ ] Production files written or changed",
    "- [ ] Configuration files written or changed",
    "- [ ] Test files written or changed",
    "",
    "## Verification",
    "",
    "- [ ] `npx ph bearshell gradle test`",
    "- [ ] `npx ph bearshell gradle build`",
    "- [ ] For a runnable Spring Boot app, `:bootJar SKIPPED` is not recorded as a passing build.",
    "- [ ] If `bootJar` fails, reconcile the Spring Boot plugin, Gradle wrapper, and JDK toolchain instead of disabling it.",
    "- [ ] For a runnable Spring Boot app: `npx ph bearshell --shell 'gradle bootRun --args=\"--server.port=<port>\"'`",
    "- [ ] If a raw shell was used directly, record why `npx ph bearshell` could not be used.",
    "",
    "## Manual QA",
    "",
    "- [ ] Ran the HTTP happy path with curl or an equivalent HTTP client.",
    "- [ ] Ran the HTTP failure path with curl or an equivalent HTTP client.",
    "- [ ] If manual QA was not possible, record the reason plus stderr and the key log lines.",
    "",
    "## Status Lifecycle",
    "",
    "- After filling this in, run `npx ph plan --report-filled implementation`.",
    "",
    "## Notes",
    "",
    "- Decisions that changed during implementation:",
    "- Remaining limitations:",
    "",
    "## Continuation",
    "",
    "- If work stops partway, fill this section in and do not claim completion.",
    "- Requirements completed:",
    "- Requirements not completed:",
    "- Last requirement or file completed:",
    "- README/plan ranges still unread:",
    "- Implementation scope still open:",
    "- Reason for stopping:",
    "- Next command or task to resume with:",
    "- Hint for the next prompt:",
    "",
  ].join("\n")
}

export function createReviewReportTemplate(inputLines: readonly string[]): string {
  return [
    "# Reviewer Review Report",
    "",
    "Role: `reviewer`",
    "Status: template",
    "",
    "## Inputs",
    "",
    ...inputLines,
    "",
    "Plan source: `.persona/workflow/plan.md`",
    "Implementation report: `.persona/workflow/implementation-report.md`",
    "",
    "## Requirements Check",
    "",
    "- [ ] The implementation report records the README/plan read method and ranges.",
    "- [ ] The implementation report records the project profile read method and ranges.",
    "- [ ] Each README requirement maps to something in the implementation.",
    "- [ ] Any requirement left unimplemented is named explicitly.",
    "",
    "## Boundary Review",
    "",
    "- [ ] The Controller handles HTTP request/response and delegation to a Service, nothing more.",
    "- [ ] The Application Service coordinates the use-case flow only.",
    "- [ ] The repository port sits in domain and its implementation in infrastructure.",
    "- [ ] Request/Response DTOs stay separate from Command/Result DTOs.",
    "- [ ] The domain model owns its own state decisions and behavior.",
    "",
    "## Verification Review",
    "",
    "- [ ] Reviewed the `npx ph bearshell gradle test` result.",
    "- [ ] Reviewed the `npx ph bearshell gradle build` result.",
    "- [ ] Confirmed the build passed without `:bootJar SKIPPED` for a runnable Spring Boot app.",
    "- [ ] For a runnable Spring Boot app, reviewed the `npx ph bearshell --shell 'gradle bootRun --args=\"--server.port=<port>\"'` result.",
    "- [ ] Reviewed the manual QA evidence for the HTTP happy path and failure path.",
    "",
    "## Status Lifecycle",
    "",
    "- After filling this in, run `npx ph plan --report-filled review`.",
    "",
    "## Remaining Limits",
    "",
    "- Recorded as smoke/review evidence, not as a product-quality guarantee.",
    "- Remaining risks:",
    "",
  ].join("\n")
}
