export function createImplementationReportTemplate(inputLines: readonly string[]): string {
  return [
    "# Jaeki Implementation Report",
    "",
    "Role: `jaeki`",
    "Status: template",
    "",
    "## Inputs",
    "",
    ...inputLines,
    "",
    "Plan source: `.persona/workflow/plan.md`",
    "",
    "## Read Coverage",
    "",
    "- README read method:",
    "- README ranges read:",
    "- Plan read method:",
    "- Plan ranges read:",
    "- Java role discovery method:",
    "- Java role files discovered:",
    "- Java role files read:",
    "- Unread ranges:",
    "- Read evidence notes:",
    "",
    "## Implemented Files",
    "",
    "- [ ] 작성/수정한 production files",
    "- [ ] 작성/수정한 configuration files",
    "- [ ] 작성/수정한 test files",
    "",
    "## Verification",
    "",
    "- [ ] `npx ph bearshell gradle test`",
    "- [ ] `npx ph bearshell gradle build`",
    "- [ ] 실행 가능한 Spring Boot 앱에서 `:bootJar SKIPPED`가 나오면 build 통과로 기록하지 않는다.",
    "- [ ] `bootJar`가 실패하면 `bootJar`를 끄지 말고 Spring Boot plugin / Gradle wrapper / JDK toolchain 호환성을 맞춘다.",
    "- [ ] 실행 가능한 Spring Boot 앱이면 `npx ph bearshell --shell 'gradle bootRun --args=\"--server.port=<port>\"'`",
    "- [ ] raw shell을 직접 썼다면 `npx ph bearshell`을 쓰지 못한 이유를 기록한다.",
    "",
    "## Manual QA",
    "",
    "- [ ] HTTP happy path를 curl 또는 동등한 HTTP client로 실행했다.",
    "- [ ] HTTP failure path를 curl 또는 동등한 HTTP client로 실행했다.",
    "- [ ] Manual QA가 불가능하면 사유와 stderr/핵심 로그를 기록한다.",
    "",
    "## Status Lifecycle",
    "",
    "- 채운 뒤에는 `npx ph plan --report-filled implementation`을 실행한다.",
    "",
    "## Notes",
    "",
    "- 구현 중 바뀐 결정:",
    "- 남은 한계:",
    "",
    "## Continuation",
    "",
    "- 중간에 멈추면 이 섹션을 채우고 완료했다고 말하지 않는다.",
    "- 완료한 요구사항:",
    "- 미완료 요구사항:",
    "- 마지막으로 완료한 요구사항/파일:",
    "- 남은 README/plan 범위:",
    "- 남은 구현 범위:",
    "- 중단 이유:",
    "- 다음에 이어서 실행할 명령/작업:",
    "- 다음 프롬프트 힌트:",
    "",
  ].join("\n")
}

export function createReviewReportTemplate(inputLines: readonly string[]): string {
  return [
    "# Roach Review Report",
    "",
    "Role: `roach`",
    "Status: template",
    "",
    "## Inputs",
    "",
    ...inputLines,
    "",
    "Plan source: `.persona/workflow/plan.md`",
    "Implementation report: `.persona/workflow/implementation-report.md`",
    "",
    "## Requirements Check",
    "",
    "- [ ] README/plan read method와 ranges가 implementation report에 남아 있다.",
    "- [ ] README 요구사항이 구현 결과와 대응된다.",
    "- [ ] 미구현 요구사항이 있으면 명시한다.",
    "",
    "## Boundary Review",
    "",
    "- [ ] Controller는 HTTP request/response와 Service 위임만 담당한다.",
    "- [ ] Application Service는 use-case 흐름만 조율한다.",
    "- [ ] Repository port는 domain에 있고 구현체는 infrastructure에 있다.",
    "- [ ] Request/Response DTO와 Command/Result DTO 경계가 분리된다.",
    "- [ ] Domain model은 자신의 상태 판단/행동을 스스로 가진다.",
    "",
    "## Verification Review",
    "",
    "- [ ] `npx ph bearshell gradle test` 결과를 확인했다.",
    "- [ ] `npx ph bearshell gradle build` 결과를 확인했다.",
    "- [ ] 실행 가능한 Spring Boot 앱에서 `:bootJar SKIPPED` 없이 build가 통과했는지 확인했다.",
    "- [ ] 실행 가능한 Spring Boot 앱이면 `npx ph bearshell --shell 'gradle bootRun --args=\"--server.port=<port>\"'` 결과를 확인했다.",
    "- [ ] HTTP happy path / failure path manual QA evidence를 확인했다.",
    "",
    "## Status Lifecycle",
    "",
    "- 채운 뒤에는 `npx ph plan --report-filled review`를 실행한다.",
    "",
    "## Remaining Limits",
    "",
    "- product-quality 보증이 아닌 smoke/review evidence로 남긴다.",
    "- 남은 리스크:",
    "",
  ].join("\n")
}
